# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b86e3cd1866c6e783fc9566572348dbdf00d915b9b6bfa564de8b29ef3900d321055f05dcc9ba70dbe208746d0bf4baa79cbdf277c274b71c1595cd3e9ecdc27

test:
  secret_key_base: e50793d8a147ab505ddd3188d452bd4e1b19fa72db942cf2acfb5d1a557f864b268744bec80b50b048ae5209cac228a2fd662269e5668994c4ad35b61eaa18b8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
